name: Build, Publish on CurseForge & Modrinth    
 
on: [ pull_request, workflow_dispatch ]           

env:                                              
  MINECRAFT_VERSION: 1.12.2                        
  JAVA_VERSION: 8      
  VERSION: 1.12.2
  RELEASE_NAME: Immersive-Intelligence-0.3.1
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}           

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build
        
      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3                                   
        with:
        
          curseforge-id: 344344                                             
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-id: q19xbT91                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
                                          

          loaders: forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

#When updating your mod you now have a few places you need to look at.

#update the version number
#in gradle.properties (typically) under mod_version = 1.1.0+1.19.2
#in .github/workflows/publish.yml under VERSION: 1.1.0+1.19.2 and RELEASE_NAME: Example Mod 1.1.0 for Minecraft 1.19.2
#update the changelog in CHANGELOG.md
