name: Notify Discord on Push

on:
  push: #Trigger On Push
    branches: [ "dev/main" ]

jobs:
  notify-discord:
    continue-on-error: true
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Notify Discord
        env:
          COMMIT_FROM: ${{ github.event.push.before }}
          COMMIT_TO: ${{ github.event.push.after }}
          WEBHOOK: ${{ secrets.DISCORD_INTERNAL_COMMITS_WEBHOOK }}
        run: chmod -R a+rX .github/workflows/* ; bash ./.github/workflows/discord_commit.sh -i
